// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function ListMusic() {
  return window['go']['main']['App']['ListMusic']();
}

export function StreamMusic(arg1, arg2) {
  return window['go']['main']['App']['StreamMusic'](arg1, arg2);
}
